@startuml Backup Job Creation - Sequence Diagram

title "Backup Job Creation - Sequence Diagram"

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 120
skinparam sequenceParticipant underline

actor User
participant "ConsoleInterface" as UI
participant "Controller" as Ctrl
participant "BackupJob" as BJ
participant "Logger" as Log
participant "FileSystem" as FS

User -> UI: Select Create Job Option
activate UI

UI -> UI: Show CreateJobDialog
activate UI #DarkSalmon

User -> UI: Fill Job Information\n(name, sourceDir, targetDir, type)

UI -> UI: Validate form data
alt form data is invalid
    UI --> User: Display form validation errors
    UI --> UI: Return to form with error messages
else form data is valid
    UI -> Ctrl: CreateBackupJob(name, sourceDir, targetDir, type)
    activate Ctrl

    Ctrl -> Ctrl: Check if job with name exists
    alt job with same name exists
        Ctrl --> UI: throw InvalidOperationException
        UI --> User: Display error: Job name already exists
    else job doesn't exist

        Ctrl -> FS: Check if source directory exists
        activate FS
        FS --> Ctrl: Return result
        deactivate FS
        
        alt source directory doesn't exist
            Ctrl --> UI: throw DirectoryNotFoundException
            UI --> User: Display error: Source directory not found
        else source directory exists
        
            Ctrl -> FS: Check if target directory exists
            activate FS
            FS --> Ctrl: Return result
            deactivate FS
            
            alt target directory doesn't exist
                Ctrl -> FS: Attempt to create target directory
                activate FS
                FS --> Ctrl: Return result
                deactivate FS

                alt directory creation failed
                    Ctrl --> UI: Display warning: Failed to create target directory
                    note over Ctrl : Only show a warning, as the failure of directory creation\ncan be due to a removable drive
                end
            end
            
            Ctrl -> BJ: create backupJob(name, sourceDir, targetDir, type, idleTime, loggerInstance)
            activate BJ
            BJ --> Ctrl: Return new job instance
            deactivate BJ
            
            Ctrl -> Ctrl: Add job to job list
            Ctrl --> UI: Return success
            deactivate Ctrl
            
            UI -> Log: Update state in logs
            activate Log
            Log --> UI: Complete
            deactivate Log
            
            UI --> User: Display Success Message
        end
    end
end

deactivate UI
deactivate UI

@enduml